[pytest]
pythonpath = src

# Add this to handle the warning
asyncio_mode = strict

# Filter out all Pydantic deprecation warnings
filterwarnings =
    ignore::pydantic.warnings.PydanticDeprecatedSince20